(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;else root.TaxEngine=api;})(typeof globalThis!=="undefined"?globalThis:this,function(){
  "use strict";
  const YEARS={
    "2025-26":{label:"2025/26",start:"2025-04-06",end:"2026-04-05",country:"England & Wales",allowance:12570,basicRate:.20,basicBand:37700,higherRate:.40,additionalRate:.45,additionalThreshold:125140,allowanceTaperStart:100000,mileageBand:10000,mileageFirst:.45,mileageAfter:.25,class4Lower:12570,class4Upper:50270,class4Main:.06,class4UpperRate:.02,financeCreditRate:.20,propertyAllowance:1000,startingSavingsBand:5000,savingsAllowanceBasic:1000,savingsAllowanceHigher:500,dividendAllowance:500,dividendBasicRate:.0875,dividendHigherRate:.3375,dividendAdditionalRate:.3935,lastUpdated:"6 April 2025",source:"GOV.UK rates and allowances"},
    "2026-27":{label:"2026/27",start:"2026-04-06",end:"2027-04-05",country:"England & Wales",allowance:12570,basicRate:.20,basicBand:37700,higherRate:.40,additionalRate:.45,additionalThreshold:125140,allowanceTaperStart:100000,mileageBand:10000,mileageFirst:.55,mileageAfter:.25,class4Lower:12570,class4Upper:50270,class4Main:.06,class4UpperRate:.02,financeCreditRate:.20,propertyAllowance:1000,startingSavingsBand:5000,savingsAllowanceBasic:1000,savingsAllowanceHigher:500,dividendAllowance:500,dividendBasicRate:.0875,dividendHigherRate:.3375,dividendAdditionalRate:.3935,lastUpdated:"17 June 2026",source:"GOV.UK rates and allowances; mileage policy update"}
  };
  const n=v=>Math.max(0,Number(v)||0),round=v=>Math.round((v+Number.EPSILON)*100)/100;
  function rulesFor(year,overrides={}){return {...(YEARS[year]||YEARS["2026-27"]),...overrides};}
  function personalAllowance(total,standard=12570,taperStart=100000){return round(Math.max(0,n(standard)-Math.max(0,n(total)-n(taperStart))/2));}
  function mileageAllowance(miles,yearOrRules){const r=typeof yearOrRules==="string"?rulesFor(yearOrRules):rulesFor("2026-27",yearOrRules);const total=n(miles),band=n(r.mileageBand)||10000;return round(Math.min(total,band)*n(r.mileageFirst)+Math.max(0,total-band)*n(r.mileageAfter));}
  function bandTax(amount,startUsed,r,rates){let remaining=n(amount),used=n(startUsed),tax=0;const basicSpace=Math.max(0,n(r.basicBand)-used),basic=Math.min(remaining,basicSpace);tax+=basic*rates.basic;remaining-=basic;used+=basic;const addStart=Math.max(n(r.basicBand),n(r.additionalThreshold)-n(r.allowance));const higherSpace=Math.max(0,addStart-used),higher=Math.min(remaining,higherSpace);tax+=higher*rates.higher;remaining-=higher;return{basic:round(basic),higher:round(higher),additional:round(remaining),tax:round(tax+remaining*rates.additional),used:round(used+higher+remaining)};}
  function incomeTax(taxable,yearOrRules){const r=typeof yearOrRules==="string"?rulesFor(yearOrRules):rulesFor("2026-27",yearOrRules),b=bandTax(taxable,0,r,{basic:n(r.basicRate),higher:n(r.higherRate),additional:n(r.additionalRate)});return{basicAmount:b.basic,higherAmount:b.higher,additionalAmount:b.additional,basicTax:round(b.basic*r.basicRate),higherTax:round(b.higher*r.higherRate),additionalTax:round(b.additional*r.additionalRate),total:b.tax};}
  function parseTaxCode(value){
    const entered=String(value||"").toUpperCase().replace(/\s+/g,""),code=entered.replace(/(W1|M1|X)$/,""),emergency=code!==entered;
    if(code==="NT")return{code:entered||"NT",type:"no-tax",allowance:0,rate:0,emergency};
    if(code==="BR")return{code:entered,type:"flat",allowance:0,rate:"basic",emergency};
    if(code==="D0")return{code:entered,type:"flat",allowance:0,rate:"higher",emergency};
    if(code==="D1")return{code:entered,type:"flat",allowance:0,rate:"additional",emergency};
    const local=code.replace(/^[CS]/,""),k=local.match(/^K(\d+)$/),standard=local.match(/^(\d+)[A-Z]+$/);
    if(k)return{code:entered,type:"k",allowance:-(Number(k[1])+1)*10,emergency};
    if(standard)return{code:entered,type:"standard",allowance:Number(standard[1])*10,emergency};
    if(local==="0T")return{code:entered,type:"zero",allowance:0,emergency};
    return{code:entered,type:"unknown",allowance:0,emergency};
  }
  function estimatePayeTax(income,code,yearOrRules){const r=typeof yearOrRules==="string"?rulesFor(yearOrRules):rulesFor("2026-27",yearOrRules),p=parseTaxCode(code),gross=n(income);if(!gross||p.type==="no-tax"||p.type==="unknown")return 0;if(p.type==="flat")return round(gross*n(r[`${p.rate}Rate`]));const taxable=Math.max(0,gross-p.allowance),tax=incomeTax(taxable,r).total;return round(p.type==="k"?Math.min(tax,gross*.5):tax);}
  function class4NI(profit,yearOrRules){const r=typeof yearOrRules==="string"?rulesFor(yearOrRules):rulesFor("2026-27",yearOrRules),p=n(profit);return round(Math.max(0,Math.min(p,r.class4Upper)-r.class4Lower)*r.class4Main+Math.max(0,p-r.class4Upper)*r.class4UpperRate);}
  function calculate(input){
    const year=input.year||"2026-27",r=rulesFor(year,input.rules),m=input.modules||{uber:true,property:true,pension:true};
    const uberIncome=m.uber===false?0:n(input.uberIncome),uberPlatformExpenses=m.uber===false?0:n(input.uberPlatformExpenses),miles=m.uber===false?0:n(input.businessMiles),mileage=m.uber===false||input.simplifiedMileage===false?0:mileageAllowance(miles,r),uberProfit=round(Math.max(0,uberIncome-uberPlatformExpenses-n(input.uberOtherExpenses)-mileage));
    const grossProperty=m.property===false?0:n(input.propertyIncome),propertyAllowance=m.property&&input.propertyAllowanceEnabled?Math.min(grossProperty,n(input.propertyAllowanceAmount||r.propertyAllowance)):0,propertyExpenses=m.property===false?0:n(input.propertyExpenses),propertyProfit=Math.max(0,grossProperty-propertyExpenses-propertyAllowance),financeCosts=m.property===false||input.financeRestrictionEnabled===false?0:n(input.financeCosts)+n(input.carriedFinanceCosts);
    const employment=m.employment?n(input.employmentIncome):0,pension=m.pension===false?0:n(input.pensionIncome),other=m.other?n(input.otherIncome):0,savings=m.savings?n(input.savingsIncome):0,dividends=m.dividends?n(input.dividendIncome):0;
    const totalIncome=round(employment+pension+other+uberProfit+propertyProfit+savings+dividends),allowance=personalAllowance(totalIncome,r.allowance,r.allowanceTaperStart);
    let allowanceLeft=allowance;const separateProperty=input.propertyTreatment==="separate",nonSavingsGross=employment+pension+other+uberProfit+(separateProperty?0:propertyProfit),nonSavingsTaxable=Math.max(0,nonSavingsGross-allowanceLeft);allowanceLeft=Math.max(0,allowanceLeft-nonSavingsGross);
    const ns=bandTax(nonSavingsTaxable,0,r,{basic:r.basicRate,higher:r.higherRate,additional:r.additionalRate});
    const propertyTaxable=separateProperty?Math.max(0,propertyProfit-allowanceLeft):0;allowanceLeft=separateProperty?Math.max(0,allowanceLeft-propertyProfit):allowanceLeft;const prop=bandTax(propertyTaxable,ns.used,r,{basic:input.propertyBasicRate??r.basicRate,higher:input.propertyHigherRate??r.higherRate,additional:input.propertyAdditionalRate??r.additionalRate}),propertySeparate=separateProperty?prop.tax:0;
    const savingsAfterAllowance=Math.max(0,savings-allowanceLeft);allowanceLeft=Math.max(0,allowanceLeft-savings);const provisionalBand=nonSavingsTaxable+propertyTaxable+savingsAfterAllowance+(dividends||0),psa=provisionalBand>r.additionalThreshold-r.allowance?0:provisionalBand>r.basicBand?n(input.personalSavingsAllowance||r.savingsAllowanceHigher):n(input.personalSavingsAllowance||r.savingsAllowanceBasic),startingSavings=input.startingSavingsRateEnabled?Math.min(savingsAfterAllowance,Math.max(0,n(r.startingSavingsBand)-nonSavingsTaxable-propertyTaxable)):0,taxableSavings=Math.max(0,savingsAfterAllowance-startingSavings-psa),sv=bandTax(taxableSavings,separateProperty?prop.used:ns.used,r,{basic:input.savingsBasicRate??r.basicRate,higher:input.savingsHigherRate??r.higherRate,additional:input.savingsAdditionalRate??r.additionalRate});
    const dividendAfterAllowance=Math.max(0,dividends-allowanceLeft-n(input.dividendAllowance||r.dividendAllowance)),dv=bandTax(dividendAfterAllowance,sv.used,r,{basic:input.dividendBasicRate??r.dividendBasicRate,higher:input.dividendHigherRate??r.dividendHigherRate,additional:input.dividendAdditionalRate??r.dividendAdditionalRate});
    const grossIncomeTax=round(ns.tax+propertySeparate+sv.tax+dv.tax),financeBase=Math.min(financeCosts,propertyProfit,Math.max(0,totalIncome-allowance)),financeCostCredit=round(Math.min(grossIncomeTax,financeBase*n(input.financeCreditRate||r.financeCreditRate))),netIncomeTax=round(Math.max(0,grossIncomeTax-financeCostCredit)),nationalInsurance=m.uber===false?0:class4NI(uberProfit,r);
    const expectedPayeTax=m.employment?estimatePayeTax(employment,input.employmentTaxCode,r):0,expectedPensionTax=m.pension?estimatePayeTax(pension,input.pensionTaxCode,r):0,payeCredit=m.employment?(input.payeTaxProvided?n(input.payeTax):expectedPayeTax):0,pensionCredit=m.pension?(input.pensionTaxProvided?n(input.pensionTaxDeducted):expectedPensionTax):0,taxAtSource=round(payeCredit+pensionCredit+(m.other?n(input.otherTaxDeducted):0)),liability=round(Math.max(0,netIncomeTax+nationalInsurance-taxAtSource)),hmrcPaid=n(input.hmrcPaid),reserve=n(input.hmrcReserve),outstanding=round(Math.max(0,liability-hmrcPaid-reserve)+n(input.catchupShortfall)),months=Math.max(1,Math.floor(n(input.catchupMonths)||n(input.monthsRemaining)||12)),rawMonthly=Math.max(n(input.minimumPayment),n(input.standardMonthlyProvision),outstanding/months),roundTo=n(input.roundPaymentTo),monthlyPayment=roundTo?Math.ceil(rawMonthly/roundTo)*roundTo:round(rawMonthly);
    const taxableIncome=round(Math.max(0,totalIncome-allowance)),band=taxableIncome>r.additionalThreshold-r.allowance?"Additional rate":taxableIncome>r.basicBand?"Higher rate":taxableIncome>0?"Basic rate":"No tax",grossTaxAndNI=round(netIncomeTax+nationalInsurance),balancingPayment=round(liability-hmrcPaid),refund=balancingPayment<0?round(-balancingPayment):0,poaEligible=liability>1000&&taxAtSource<grossTaxAndNI*.8,standardPoa=poaEligible?round(liability/2):0,firstPaymentOnAccount=input.reducePaymentsOnAccount?Math.min(standardPoa,n(input.reducedPaymentOnAccount)):standardPoa,secondPaymentOnAccount=firstPaymentOnAccount,totalCashDue=round(Math.max(0,balancingPayment)+firstPaymentOnAccount);
    return{year,rules:r,pension,employment,other,savings,dividends,propertyIncome:grossProperty,propertyExpenses,propertyAllowance,financeCosts,propertyProfit,uberIncome,uberPlatformExpenses,uberOtherExpenses:n(input.uberOtherExpenses),miles,mileage,uberProfit,totalIncome,adjustedNetIncome:totalIncome,allowance,taxableIncome,basicAmount:ns.basic,higherAmount:ns.higher,additionalAmount:ns.additional,basicTax:round(ns.basic*r.basicRate),higherTax:round(ns.higher*r.higherRate),additionalTax:round(ns.additional*r.additionalRate),savingsTax:sv.tax,dividendTax:dv.tax,propertySeparateTax:propertySeparate,grossIncomeTax,financeCostCredit,netIncomeTax,nationalInsurance,expectedPayeTax,expectedPensionTax,payeCredit,pensionCredit,taxAtSource,liability,paid:hmrcPaid,reserve,outstanding,monthlyPayment,balancingPayment,refund,poaEligible,firstPaymentOnAccount,secondPaymentOnAccount,totalCashDue,band};
  }
  return{YEARS,rulesFor,personalAllowance,mileageAllowance,incomeTax,parseTaxCode,estimatePayeTax,class4NI,calculate};
});
